export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const ADD_TELESCOPES = 'ADD_TELESCOPES';
export const TELESCOPES_LOADING = 'TELESCOPES_LOADING';
export const TELESCOPES_FAILED = 'TELESCOPES_FAILED';

export const ADD_SPACEPORTS = 'ADD_SPACEPORTS';
export const SPACEPORTS_LOADING = 'SPACEPORTS_LOADING';
export const SPACEPORTS_FAILED = 'SPACEPORTS_FAILED';

export const ADD_PARTNERS = 'ADD_PARTNERS';
export const PARTNERS_LOADING = 'PARTNERS_LOADING';
export const PARTNERS_FAILED = 'PARTNERS_FAILED'; 