export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const ADD_TELESCOPES = 'ADD_TELESCOPES';
export const TELESCOPES_LOADING = 'TELESCOPES_LOADING';
export const TELESCOPES_FAILED = 'TELESCOPES_FAILED';

export const ADD_SPACEPORTS = 'ADD_SPACEPORTS';
export const SPACEPORTS_LOADING = 'SPACEPORTS_LOADING';
export const SPACEPORTS_FAILED = 'SPACEPORTS_FAILED';

export const ADD_ROVERS = 'ADD_ROVERS';
export const ROVERS_LOADING = 'ROVERS_LOADING';
export const ROVERS_FAILED = 'ROVERS_FAILED'; 